version: "3"
services:

  node-js-1:
    image: mzain/java-test-app1
    ports:
      - "7766:8080"
    container_name: java-test-app1
  
  node-js-2:
    build: ./app2
    ports:
       - "8866:8080"
    container_name: java-test-app2

  nginx:
    image: mzain/reverse
    ports:
      - "80:80"
    container_name: project_reverse-proxy
